INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 00:48:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 00:57:32] "GET /api/v1/offer/all HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 00:58:03] "[31m[1mPUT /api/v1/offer/all HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 00:58:10] "GET /api/v1/offer/all HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /api/v1/offer/all [GET]
Traceback (most recent call last):
  File "/home/daniel/Documents/CS/Projects/RT/server/api/api_offer.py", line 16, in get_all_offers
    offers = session.db_offers.Offer().all()
NameError: name 'session' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/daniel/Documents/CS/Projects/RT/server/api/api_offer.py", line 19, in get_all_offers
    current_app.logger.info('%s failed to log in', user.username)
NameError: name 'user' is not defined
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 00:59:58] "[35m[1mGET /api/v1/offer/all HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /api/v1/offer/all [GET]
Traceback (most recent call last):
  File "/home/daniel/Documents/CS/Projects/RT/server/api/api_offer.py", line 16, in get_all_offers
    offers = session.db_offers.Offer().all()
NameError: name 'session' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/daniel/Documents/CS/Projects/RT/server/api/api_offer.py", line 20, in get_all_offers
    current_app.logger.info('%s failed to log in', user.username)
NameError: name 'user' is not defined
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 01:00:52] "[35m[1mGET /api/v1/offer/all HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /api/v1/offer/all [GET]
Traceback (most recent call last):
  File "/home/daniel/Documents/CS/Projects/RT/server/api/api_offer.py", line 16, in get_all_offers
    offers = session.db_offers.Offer().all()
NameError: name 'session' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daniel/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/daniel/Documents/CS/Projects/RT/server/api/api_offer.py", line 20, in get_all_offers
    current_app.logger.info('%s failed to log in', user.username)
NameError: name 'user' is not defined
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 01:01:37] "[35m[1mGET /api/v1/offer/all HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Jan/2023 01:02:35] "[35m[1mGET /api/v1/offer/all HTTP/1.1[0m" 500 -
